name: Build MosDNS Rules

on:
  schedule:
    - cron: '0 20 * * *' # UTC 20:00 即北京时间凌晨 04:00
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'rules.txt'
      - '.github/workflows/update.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Setup Go Environment
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: false

      - name: Install v2dat
        run: go install github.com/urlesistiana/v2dat@latest

      - name: Download dat files
        run: |
          wget -qO geosite.dat https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat
          wget -qO geoip.dat https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip.dat

      - name: Unpack rules based on rules.txt
        run: |
          mkdir -p temp_publish/geosite temp_publish/geoip
          
          while IFS= read -r line || [ -n "$line" ]; do
            [[ -z "$line" || "$line" == \#* ]] && continue
            
            type=$(echo "$line" | cut -d'-' -f1)
            tag=$(echo "$line" | cut -d'-' -f2-)
            
            echo "正在处理: 类别=$type, 标签=$tag"
            
            if [[ "$type" == "geosite" ]]; then
              v2dat unpack geosite -o temp_publish/geosite -f "$tag" geosite.dat
            elif [[ "$type" == "geoip" ]]; then
              v2dat unpack geoip -o temp_publish/geoip -f "$tag" geoip.dat
            fi
          done < rules.txt

      - name: Force push to meta branch
        run: |
          cd temp_publish
          
          git init
          git checkout -b meta
          
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          git add .
          
          export TZ='Asia/Shanghai'
          COMMIT_MSG="Released on $(date +'%Y-%m-%d %H:%M')"
          
          git commit -m "$COMMIT_MSG"
          
          git push -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git meta

      - name: Cleanup
        run: |
          rm -rf temp_publish geosite.dat geoip.dat